server:
  port: 9090
dubbo:
  application:
    name: consumer-server
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
  scan:
    base-packages: com.ddz.service.impl
  consumer:
    check: false # 全局都不检查 服务提供端
    timeout: 2000 # 全局服务调用超时时间 2s
    retries: 5 # 全局服务超时 重试次数 --------------------注意幂等性问题