dubbo:
  application:
    name: provider-server
  registry:   #注册中心
    address: 127.0.0.1:2181
    protocol: zookeeper
  protocol:   #dubbo的通信配置
    name: dubbo
  #    port: 20880
  scan:
    base-packages: com.zb.service.impl
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: ok
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    auto-mapping-behavior: full